import type { Airport, Airline, Flight } from "./types";

export const AIRPORTS: Record<string, Airport> = {
  JFK: { code: "JFK", city: "New York", name: "John F. Kennedy Intl", country: "USA" },
  LAX: { code: "LAX", city: "Los Angeles", name: "Los Angeles Intl", country: "USA" },
  SFO: { code: "SFO", city: "San Francisco", name: "San Francisco Intl", country: "USA" },
  ORD: { code: "ORD", city: "Chicago", name: "O'Hare Intl", country: "USA" },
  ATL: { code: "ATL", city: "Atlanta", name: "Hartsfield-Jackson", country: "USA" },
  MIA: { code: "MIA", city: "Miami", name: "Miami Intl", country: "USA" },
  SEA: { code: "SEA", city: "Seattle", name: "Seattle-Tacoma", country: "USA" },
  BOS: { code: "BOS", city: "Boston", name: "Logan Intl", country: "USA" },
  LHR: { code: "LHR", city: "London", name: "Heathrow", country: "UK" },
  CDG: { code: "CDG", city: "Paris", name: "Charles de Gaulle", country: "France" },
  FRA: { code: "FRA", city: "Frankfurt", name: "Frankfurt am Main", country: "Germany" },
  AMS: { code: "AMS", city: "Amsterdam", name: "Schiphol", country: "Netherlands" },
  DXB: { code: "DXB", city: "Dubai", name: "Dubai Intl", country: "UAE" },
  SIN: { code: "SIN", city: "Singapore", name: "Changi", country: "Singapore" },
  NRT: { code: "NRT", city: "Tokyo", name: "Narita Intl", country: "Japan" },
  HKG: { code: "HKG", city: "Hong Kong", name: "Hong Kong Intl", country: "HK" },
  SYD: { code: "SYD", city: "Sydney", name: "Kingsford Smith", country: "Australia" },
  DEL: { code: "DEL", city: "New Delhi", name: "Indira Gandhi Intl", country: "India" },
  BOM: { code: "BOM", city: "Mumbai", name: "Chhatrapati Shivaji", country: "India" },
  BLR: { code: "BLR", city: "Bengaluru", name: "Kempegowda Intl", country: "India" },
};

export const AIRLINES: Record<string, Airline> = {
  SKY: { code: "SKY", name: "SkyJet Airways", logo: "✈️" },
  CLD: { code: "CLD", name: "CloudAir", logo: "☁️" },
  FWR: { code: "FWR", name: "Fly with Ram Airlines", logo: "🛫" },
  AZR: { code: "AZR", name: "Azure Wings", logo: "🟦" },
  STR: { code: "STR", name: "StarLine Airways", logo: "⭐" },
  ORB: { code: "ORB", name: "OrbitAir", logo: "🪐" },
};

const ISO = (d: string, t: string) => `${d}T${t}:00`;

const BASE_DATE = "2026-08-15"; // future date so flights are always "available"

/**
 * In-memory flight catalog. Stable IDs/flight numbers so Playwright tests
 * can target them. Covers major US, EU, Asia routes with various stops,
 * airlines, cabin classes, and one intentionally-out-of-stock flight.
 */
export const CATALOG: Flight[] = [
  {
    id: "f-001",
    flightNumber: "FWR 101",
    airline: AIRLINES.FWR,
    origin: AIRPORTS.JFK,
    destination: AIRPORTS.LAX,
    departureTime: ISO(BASE_DATE, "08:30"),
    arrivalTime: ISO(BASE_DATE, "11:45"),
    durationMins: 365,
    stops: 0,
    price: 299,
    currency: "USD",
    cabinClasses: ["economy", "premium", "business", "first"],
    seatsLeft: 24,
    aircraft: "Boeing 787-9",
    tags: ["nonstop", "morning", "popular"],
  },
  {
    id: "f-002",
    flightNumber: "SKY 245",
    airline: AIRLINES.SKY,
    origin: AIRPORTS.JFK,
    destination: AIRPORTS.LAX,
    departureTime: ISO(BASE_DATE, "14:20"),
    arrivalTime: ISO(BASE_DATE, "17:55"),
    durationMins: 395,
    stops: 0,
    price: 249,
    currency: "USD",
    cabinClasses: ["economy", "premium", "business"],
    seatsLeft: 12,
    aircraft: "Airbus A321neo",
    tags: ["nonstop", "afternoon", "budget"],
  },
  {
    id: "f-003",
    flightNumber: "CLD 88",
    airline: AIRLINES.CLD,
    origin: AIRPORTS.JFK,
    destination: AIRPORTS.LAX,
    departureTime: ISO(BASE_DATE, "06:00"),
    arrivalTime: ISO(BASE_DATE, "11:30"),
    durationMins: 510,
    stops: 1,
    stopCities: ["ORD"],
    price: 189,
    currency: "USD",
    cabinClasses: ["economy"],
    seatsLeft: 60,
    aircraft: "Boeing 737 MAX",
    tags: ["1-stop", "early", "cheapest"],
  },
  {
    id: "f-004",
    flightNumber: "FWR 202",
    airline: AIRLINES.FWR,
    origin: AIRPORTS.SFO,
    destination: AIRPORTS.NRT,
    departureTime: ISO(BASE_DATE, "11:00"),
    arrivalTime: ISO(BASE_DATE + "T11:00", "11:00"),
    durationMins: 660,
    stops: 0,
    price: 899,
    currency: "USD",
    cabinClasses: ["economy", "premium", "business", "first"],
    seatsLeft: 8,
    aircraft: "Boeing 777-300ER",
    tags: ["nonstop", "long-haul", "international"],
  },
  {
    id: "f-005",
    flightNumber: "AZR 7",
    airline: AIRLINES.AZR,
    origin: AIRPORTS.LHR,
    destination: AIRPORTS.JFK,
    departureTime: ISO(BASE_DATE, "09:15"),
    arrivalTime: ISO(BASE_DATE, "12:30"),
    durationMins: 495,
    stops: 0,
    price: 459,
    currency: "USD",
    cabinClasses: ["economy", "premium", "business", "first"],
    seatsLeft: 18,
    aircraft: "Airbus A350-1000",
    tags: ["nonstop", "transatlantic", "international"],
  },
  {
    id: "f-006",
    flightNumber: "STR 55",
    airline: AIRLINES.STR,
    origin: AIRPORTS.DXB,
    destination: AIRPORTS.SIN,
    departureTime: ISO(BASE_DATE, "22:45"),
    arrivalTime: ISO(BASE_DATE + "T10:15", "10:15"),
    durationMins: 450,
    stops: 0,
    price: 549,
    currency: "USD",
    cabinClasses: ["economy", "business", "first"],
    seatsLeft: 22,
    aircraft: "Airbus A380-800",
    tags: ["nonstop", "red-eye", "luxury"],
  },
  {
    id: "f-007",
    flightNumber: "ORB 333",
    airline: AIRLINES.ORB,
    origin: AIRPORTS.DEL,
    destination: AIRPORTS.BOM,
    departureTime: ISO(BASE_DATE, "07:00"),
    arrivalTime: ISO(BASE_DATE, "08:30"),
    durationMins: 90,
    stops: 0,
    price: 79,
    currency: "USD",
    cabinClasses: ["economy", "business"],
    seatsLeft: 100,
    aircraft: "Airbus A320neo",
    tags: ["nonstop", "short-haul", "domestic"],
  },
  {
    id: "f-008",
    flightNumber: "FWR 404",
    airline: AIRLINES.FWR,
    origin: AIRPORTS.SYD,
    destination: AIRPORTS.LAX,
    departureTime: ISO(BASE_DATE, "13:00"),
    arrivalTime: ISO(BASE_DATE + "T09:30", "09:30"),
    durationMins: 810,
    stops: 1,
    stopCities: ["HKG"],
    price: 1199,
    currency: "USD",
    cabinClasses: ["economy", "premium", "business", "first"],
    seatsLeft: 0, // intentionally sold out
    aircraft: "Boeing 787-9",
    tags: ["1-stop", "long-haul", "international", "sold-out"],
  },
  {
    id: "f-009",
    flightNumber: "SKY 100",
    airline: AIRLINES.SKY,
    origin: AIRPORTS.ATL,
    destination: AIRPORTS.MIA,
    departureTime: ISO(BASE_DATE, "10:00"),
    arrivalTime: ISO(BASE_DATE, "12:00"),
    durationMins: 120,
    stops: 0,
    price: 129,
    currency: "USD",
    cabinClasses: ["economy", "premium"],
    seatsLeft: 45,
    aircraft: "Boeing 737-800",
    tags: ["nonstop", "short-haul", "domestic"],
  },
  {
    id: "f-010",
    flightNumber: "CLD 22",
    airline: AIRLINES.CLD,
    origin: AIRPORTS.SEA,
    destination: AIRPORTS.BOS,
    departureTime: ISO(BASE_DATE, "23:30"),
    arrivalTime: ISO(BASE_DATE + "T07:45", "07:45"),
    durationMins: 315,
    stops: 1,
    stopCities: ["ORD"],
    price: 219,
    currency: "USD",
    cabinClasses: ["economy"],
    seatsLeft: 30,
    aircraft: "Airbus A321",
    tags: ["1-stop", "red-eye"],
  },
  {
    id: "f-011",
    flightNumber: "AZR 99",
    airline: AIRLINES.AZR,
    origin: AIRPORTS.CDG,
    destination: AIRPORTS.DXB,
    departureTime: ISO(BASE_DATE, "15:30"),
    arrivalTime: ISO(BASE_DATE + "T00:45", "00:45"),
    durationMins: 435,
    stops: 0,
    price: 389,
    currency: "USD",
    cabinClasses: ["economy", "premium", "business"],
    seatsLeft: 14,
    aircraft: "Boeing 777-200ER",
    tags: ["nonstop", "international"],
  },
  {
    id: "f-012",
    flightNumber: "STR 17",
    airline: AIRLINES.STR,
    origin: AIRPORTS.HKG,
    destination: AIRPORTS.SIN,
    departureTime: ISO(BASE_DATE, "18:00"),
    arrivalTime: ISO(BASE_DATE, "22:15"),
    durationMins: 255,
    stops: 0,
    price: 159,
    currency: "USD",
    cabinClasses: ["economy", "business"],
    seatsLeft: 80,
    aircraft: "Airbus A350-900",
    tags: ["nonstop", "short-haul", "international"],
    a11yIssues: ["low-contrast-price", "missing-aria-on-route-toggle"],
  },
];

export function findFlight(id: string): Flight | undefined {
  return CATALOG.find((f) => f.id === id);
}

export function findFlightByNumber(fn: string): Flight | undefined {
  return CATALOG.find((f) => f.flightNumber === fn);
}

/** Generate a 6-char PNR (booking reference). */
export function generatePNR(): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no I, O, 0, 1
  let pnr = "";
  for (let i = 0; i < 6; i++) {
    pnr += chars[Math.floor(Math.random() * chars.length)];
  }
  return pnr;
}
